# Generated by Django 2.2.7 on 2019-11-08 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='second_day',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
