# Generated by Django 2.2.7 on 2019-11-08 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20191108_1224'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='date',
            new_name='exam_date',
        ),
    ]
